<?php

/**
 * @file
 * Contains localgov_extra_layouts.module.
 */

declare(strict_types=1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function localgov_extra_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the localgov_extra_layouts module.
    case 'help.page.localgov_extra_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Localgov Extra Layouts module') . '</p>';
      return $output;

    default:
  }
}
